console.log('First message!');
setTimeout(() => {
    console.log('This message will always run last...');
}, 7);
console.log('1 message!');
console.log('2 message!');
console.log('2 message!');
console.log('3 message!');
console.log('4 message!');
console.log('5 message!');
console.log('6 message!');
console.log('7 message!');
console.log('8 message!');
console.log('9 message!');
console.log('10 message!');
setTimeout(() => {
    console.log('222222 This message will always run last...');
}, 0);
console.log('11 message!');
console.log('12 message!');
console.log('11 message!');
console.log('12 message!');
console.log('11 message!');
console.log('12 message!');
console.log('11 message!');
console.log('12 message!');
console.log('11 message!');
console.log('12 message!');
console.log('11 message!');
console.log('12 message!');
